MODEL:
  architecture:  "MViT"
  # img_res: 24
  max_seq_len: 60
  num_channels: 11
  num_features: 16
  # num_classes: 20
  ignore_background: [0]
  dropout: 0.
  # patch_size: 2
  # dim: 128
  temporal_depth: 4
  spatial_depth: 4
  # heads: 4
  pool: 'cls'
  dim_head: 32
  # dim_head = dim / head
  emb_dropout: 0.
  scale_dim: 4

  device: 'cpu'

  phenology_num: 5
  phenology_prior: [[50, 100, 150, 200, 250], [25, 64, 142, 214, 273], [26, 78, 130, 182, 234], [27, 92, 157, 222, 287], [28, 106, 184, 262, 340], 
  [84, 106, 129, 301, 331], [85, 120, 155, 190, 225], [86, 134, 181, 228, 275], [87, 148, 207, 266, 325], 
  [88, 162, 233, 304, 361], [144, 162, 181, 338, 356], [145, 196, 247, 298, 349], [146, 210, 313, 316, 352], 
  [16, 24, 49, 156, 269], [19, 64, 98, 145, 258], [46, 87, 95, 162, 278], [49, 148, 195, 275, 325],
  [41, 162, 198, 245, 296], [114, 163, 198, 215, 356], [50, 100, 150, 200, 250]]

  cls_token_num: 20

  in_feat_dim: 128
  inter_channels: [32, 48, 72, 108]
  num_head: 4
  mlp_ratio: 8
  num_block: 3
  final_embedding_dim: 128
  num_classes: 20
  patch_size: 2
  img_res: 24

DATASETS:
  train:
    dataset: "PASTIS24_fold2"
    label_map:
    max_seq_len: 60
    batch_size: 8
    extra_data:
    num_workers: 4

  eval:
    dataset: "PASTIS24_fold2"
    label_map:
    max_seq_len: 60
    batch_size: 24
    extra_data:
    num_workers: 4

  test:
    dataset: "PASTIS24_fold2"
    label_map:
    max_seq_len: 60
    batch_size: 24
    extra_data:
    num_workers: 4

SOLVER:
  num_epochs: 100
  num_warmup_epochs: 10
  steps: (0, 80000)
  loss_function:  masked_cross_entropy
  class_weights:
  lr_scheduler: 'cosine'
  lr_base: 1e-3
  lr_min: 5e-6
  # lr_start: 1e-8
  lr_start: 5e-3
  lr_decay: 0.97
  num_cycles: 1
  reset_lr: True   # resets lr to base value when loading pretrained model
  weight_decay: 0.000

CHECKPOINT:
  # load_from_checkpoint: 'D:\\AMViT\\PASTIS24_checkpoints\\TSViT_fold1'
  load_from_checkpoint: False
  partial_restore: False
  save_path: '/root/autodl-tmp/MViT_SavedModels/PASTIS24_fold2'
  train_metrics_steps: 50
  eval_steps: 100
  save_steps: 20000000000
